<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="2" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="30681" started-at="2021-03-18T14:33:42 CDT" finished-at="2021-03-18T14:34:12 CDT">
    <groups>
    </groups>
    <test name="Test" duration-ms="30681" started-at="2021-03-18T14:33:42 CDT" finished-at="2021-03-18T14:34:12 CDT">
      <class name="Automation.Test3">
        <test-method status="PASS" signature="SetUpTest()[pri:0, instance:Automation.Test3@2a40cd94]" name="SetUpTest" is-config="true" duration-ms="1433" started-at="2021-03-18T14:33:44 CDT" finished-at="2021-03-18T14:33:45 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUpTest -->
        <test-method status="PASS" signature="BeginTest()[pri:0, instance:Automation.Test3@2a40cd94]" name="BeginTest" duration-ms="6347" started-at="2021-03-18T14:33:49 CDT" finished-at="2021-03-18T14:33:55 CDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Testing for Exception] but found [Test 3: Preparing for test]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Testing for Exception] but found [Test 3: Preparing for test]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Automation.Test3.BeginTest(Test3.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeginTest -->
        <test-method status="PASS" signature="AfterTest()[pri:0, instance:Automation.Test3@2a40cd94]" name="AfterTest" is-config="true" duration-ms="8689" started-at="2021-03-18T14:34:04 CDT" finished-at="2021-03-18T14:34:12 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterTest -->
      </class> <!-- Automation.Test3 -->
      <class name="Automation.Test1">
        <test-method status="PASS" signature="SetUpTest()[pri:0, instance:Automation.Test1@6c9f5c0d]" name="SetUpTest" is-config="true" duration-ms="2440" started-at="2021-03-18T14:33:42 CDT" finished-at="2021-03-18T14:33:44 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUpTest -->
        <test-method status="PASS" signature="Test()[pri:0, instance:Automation.Test1@6c9f5c0d]" name="Test" duration-ms="3066" started-at="2021-03-18T14:33:46 CDT" finished-at="2021-03-18T14:33:49 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Automation.Test1@6c9f5c0d]" name="afterTest" is-config="true" duration-ms="8664" started-at="2021-03-18T14:33:55 CDT" finished-at="2021-03-18T14:34:04 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- Automation.Test1 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
